#! /bin/sh

sxhkd &
picom -b
feh --bg-fill /home/marcelo/Documentos/themes/wallpapers/wallhaven.jpg
$HOME/.config/polybar/launch.sh &

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
bcpc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9

bspc config border_width         3
bspc config normal_border_color  "#2e3440"
bspc config active_border_color  "#4c566a"
bspc config focused_border_color "#8fbcbb"
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gnome-calculator state=floating
