#! /bin/sh
xsetroot -cursor_name left_ptr
sxhkd &
picom -b
feh --bg-fill /home/marcelo/Documentos/themes/wallpapers/archnord.png
$HOME/.config/polybar/launch.sh &
xmodmap $HOME/.Xmodmap &
pidof bspswallow || bspswallow &

# Change WN name for java applications (specifically jmeter)
# https://wiki.archlinux.org/index.php/Bspwm#Problems_with_Java_applications
#wmname LG3D

nmonitors=$(bspc query -M --names | wc -l)

case "$nmonitors" in
  2)
    bspc monitor eDP-1  -d 1
    bspc monitor HDMI-1 -d 2 3 4 5 6 7 8 9
    ;;
  *)
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
    ;;
esac

bspc config border_width         3
bspc config normal_border_color  "#2e3440"
bspc config active_border_color  "#4c566a"
bspc config focused_border_color "#88c0d0"
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_monitor true

bspc rule -a Chromium desktop='^9'
bspc rule -a firefox desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a Thunar desktop='^4'
bspc rule -a Slack desktop='^5'
bspc rule -a Deadbeef desktop='^6'
bspc rule -a org.remmina.Remmina desktop='^7' state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Transmission-gtk desktop='^9' state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gnome-calculator state=floating
